/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.util.Map;
import model.Commande;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import service.CommandeService;

/**
 *
 * @author OTHMANE
 */
public class ChiffreAffaires extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChiffreAffaires
     */
    CommandeService ms;

    public ChiffreAffaires() throws Exception {
        initComponents();
        ms = new CommandeService();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        Map<String, Double> total = ms.chiffreAffaireParPlat();

        for (Map.Entry<String, Double> entry : total.entrySet()) {
            String plat = entry.getKey();
            Double valeur = entry.getValue();
            dataset.addValue(valeur, "Recette", plat);
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Chiffre d'affaire du Restaurant",
                "Type",
                "Montant",
                dataset
        );

        ChartFrame frame = new ChartFrame("Statistiques", chart);
        frame.setSize(1200, 800);
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
