/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import service.CommandeService;
import java.util.List;
import java.util.Map;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author OTHMANE
 */
public class PlatsPopulaires extends javax.swing.JInternalFrame {

    /**
     * Creates new form PlatsPopulaires
     */
    CommandeService ms;

    public PlatsPopulaires() throws Exception {
        initComponents();
        ms = new CommandeService();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        List<Map<String, Object>> data = ms.platsPopulairesRestau();

        for (Map<String, Object> row : data) {
            String nomPlat = (String) row.get("nom_plat");
            int quantite = ((Number) row.get("total_commande")).intValue();
            dataset.addValue(quantite, "Quantité", nomPlat);
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Plats les plus populaires",
                "Plat",
                "Quantité vendue",
                dataset
        );
        setClosable(true);       
        setIconifiable(true);     
        setMaximizable(true);     
        setResizable(true);       
        setTitle("Plats les plus populaires"); 
        
        

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(1200, 800));

        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().removeAll();
        getContentPane().add(chartPanel, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
        pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
